### PR TITLE
Use new version of envconsul with env var bug fix

### PR DESCRIPTION
**Pull request by todoubled**
Fixes https://github.com/hashicorp/envconsul/pull/100
- [x] upload new zip to S3 bucket

### CODE REVIEW

**Comment by todoubled** [comment]
@hellodigit/engineering ready for review

**Comment by sudothinker** [comment]
👍 

We need to do any testing of this on staging before rolling out?

**Comment by todoubled** [comment]
@sudothinker this is fully tested on staging and ready to deploy to production, I just need your help with https://gist.github.com/todoubled/bb10406376004caed1074c01f8dab5b5

**Comment by todoubled** [comment]
This is looking good in prod now

**Pull request merged**
